[package]
name = "formwork-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
formwork-blueprint = { workspace = true }
formwork-compile = { workspace = true }
formwork-confine = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-std", "sync"] }

[dev-dependencies]
formwork-detect = { workspace = true }
