//! Deterministic SBPL (Seatbelt profile language) generation for the macOS confiner.
//!
//! SBPL is last-match-wins, so ordering encodes the policy: `(allow default)` for transparency
//! (FW-TRA2), then `(deny network*)` + optional port re-allows, then reads, writes, exec. Within
//! each fs section the order is: grants, credential-floor denies (FW-CRED4), typed-exclusion
//! re-allows clamped to the grant surface (FW-CRED5 -- so `--allow-cred aws` lifts the any-depth
//! backstop inside `~/.aws/**` without widening anything), then operator subtract holes last --
//! an operator deny is never lifted by anything.

use formwork_blueprint::{
    intersect_grants, Channel, ChannelPolicy, ExecPosture, IsolateMember, NetPosture, PathPattern,
    ReadMode,
};

use crate::CompileInput;

/// Pure and deterministic.
pub fn render(input: &CompileInput) -> String {
    let mut b = String::new();
    b.push_str("(version 1)\n");
    b.push_str(";; Generated by formwork-compile. Do not edit.\n");
    b.push_str("(allow default)\n");

    render_net(
        &mut b,
        &input.net,
        input.gateway_port,
        &input.unix_socket_grants,
    );
    render_reads(
        &mut b,
        input.read_mode,
        &input.effective_reads,
        &input.subtract,
        &input.floor,
        &input.floor_exempt,
    );
    render_writes(
        &mut b,
        &input.writes,
        &input.writes_no_create,
        &input.subtract,
        &input.write_subtract,
        &input.floor,
        &input.floor_exempt,
    );
    render_exec(&mut b, &input.exec);
    render_baseline(
        &mut b,
        &input.channels,
        (!input.keyring_lifted).then_some(input.keyring_services.as_slice()),
    );
    render_isolate(&mut b, &input.isolate);
    if let Some(marker) = &input.session_marker {
        // Last, so no rule above shadows either half (FW-EGR9).
        b.push_str("\n;; session marker for the egress listener's peer check (FW-EGR9)\n");
        b.push_str(&format!(
            "(deny mach-lookup (global-name \"{}\"))\n(allow mach-lookup (global-name \"{}\"))\n",
            marker.denied_service(),
            marker.allowed_service()
        ));
    }

    b
}

/// A Mach service name, matched exactly or by prefix.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Service {
    Exact(&'static str),
    Prefix(&'static str),
}

impl Service {
    pub fn matches(self, name: &str) -> bool {
        match self {
            Service::Exact(s) => name == s,
            Service::Prefix(p) => name.starts_with(p),
        }
    }

    fn filter(self) -> String {
        match self {
            Service::Exact(s) => format!("(global-name \"{s}\")"),
            Service::Prefix(p) => format!("(global-name-regex #\"^{}\")", regex_escape(p)),
        }
    }
}

/// The Mach services each channel's clients reach, as the characterization suite observed them on
/// macOS 14 and 15 (FEP-5 §6.3 C3): its tests run every channel's probe with each lookup reported,
/// and fail when a probe reaches a service this map does not name, or still works once the
/// channel's services are denied. Camera and microphone have no device on a hosted runner and are
/// not characterized.
pub const CHANNEL_SERVICES: &[(Channel, &[Service])] = &[
    (
        Channel::RunOutside,
        &[Service::Exact("com.apple.coreservices.appleevents")],
    ),
    (Channel::OpenUrl, &[]),
    (
        Channel::Clipboard,
        &[Service::Prefix("com.apple.pasteboard.")],
    ),
    (
        Channel::Screen,
        &[
            Service::Exact("com.apple.windowserver.active"),
            Service::Exact("com.apple.CARenderServer"),
            Service::Exact("com.apple.replayd"),
            Service::Prefix("com.apple.screencapture"),
        ],
    ),
    (Channel::Camera, &[Service::Prefix("com.apple.cmio.")]),
    (
        Channel::Microphone,
        &[Service::Exact("com.apple.audio.AudioComponentRegistrar")],
    ),
];

/// The Mach services a channel reaches.
pub fn channel_services(channel: Channel) -> &'static [Service] {
    CHANNEL_SERVICES
        .iter()
        .find(|(c, _)| *c == channel)
        .map(|(_, s)| *s)
        .unwrap_or(&[])
}

/// The SBPL that closes one channel (FW-ISO13): operation-level denies where one operation is the
/// channel (`appleevent-send`, `lsopen`, launchd `job-creation`), and the channel's Mach services.
fn channel_rules(channel: Channel) -> Vec<String> {
    let mut rules: Vec<String> = match channel {
        Channel::RunOutside => vec![
            "(deny appleevent-send)".to_string(),
            "(deny job-creation)".to_string(),
        ],
        // `open-url` is brokered through the Gateway (FW-ISO18); LaunchServices stays denied even
        // when the channel is lifted, so this rule is emitted unconditionally below.
        Channel::OpenUrl => vec!["(deny lsopen)".to_string()],
        _ => Vec::new(),
    };
    let services = channel_services(channel);
    if !services.is_empty() {
        let filters: Vec<String> = services.iter().map(|s| s.filter()).collect();
        rules.push(format!("(deny mach-lookup {})", filters.join(" ")));
    }
    rules
}

/// The mechanism behind a channel's deny, for the report's reason text.
pub fn channel_mechanism(channel: Channel) -> &'static str {
    match channel {
        Channel::RunOutside => "appleevent-send, launchd job creation and the AppleEvents service",
        Channel::OpenUrl => "lsopen",
        Channel::Clipboard => "com.apple.pasteboard.* lookups",
        Channel::Screen => "WindowServer, CARenderServer and screen-capture service lookups",
        Channel::Camera => "com.apple.cmio.* lookups",
        Channel::Microphone => "audio component registrar lookups",
    }
}

/// The anti-shedding baseline on macOS (FW-ISO8 as amended): host-service channels not lifted
/// (FW-ISO13), the keychain's services unless `os-keyring` is lifted (FW-CRED13), and privileged
/// kernel ports (FW-ISO14). Other processes' environments (FW-ISO16) have no rule here: the
/// `kern.procargs2` sysctl that returns them is not mediated by Seatbelt (characterization C5).
fn render_baseline(b: &mut String, channels: &ChannelPolicy, keyring: Option<&[String]>) {
    b.push_str("\n;; host-service channel baseline (FW-ISO13)\n");
    for channel in Channel::ALL {
        // LaunchServices is never lifted: `open-url` is brokered by the Gateway (FW-ISO18).
        if channels.lifted(channel) && channel != Channel::OpenUrl {
            continue;
        }
        for rule in channel_rules(channel) {
            b.push_str(&rule);
            b.push('\n');
        }
    }
    // Characterized (C3): `security` reaches the keychain through these alone, while TLS clients
    // (curl, git, Node, URLSession, Go) verify through `trustd` and keep working without them.
    if let Some(services) = keyring.filter(|s| !s.is_empty()) {
        b.push_str(";; the keychain (FW-CRED13): lifted by allow-credentials = [\"os-keyring\"]\n");
        let filters: Vec<String> = services
            .iter()
            .map(|s| format!("(global-name \"{}\")", escape(s)))
            .collect();
        b.push_str(&format!("(deny mach-lookup {})\n", filters.join(" ")));
    }
    b.push_str(";; privileged interfaces (FW-ISO14)\n");
    b.push_str("(deny mach-priv-host-port)\n");
    b.push_str("(deny mach-priv-task-port)\n");
}

/// The opt-in isolation tier on macOS (FW-ISO10). `same-sandbox` re-allows the session's own
/// process management (shell job control, `make -j`, worker pools).
fn render_isolate(b: &mut String, isolate: &[IsolateMember]) {
    if isolate.is_empty() {
        return;
    }
    b.push_str("\n;; isolation tier (FW-ISO10)\n");
    if isolate.contains(&IsolateMember::Processes) {
        // `same-sandbox` is exactly the session: every process the workload starts carries this
        // profile, reparented or regrouped, and no other process does. The denies are whole, not
        // `(target others)`, which leaves out the session's process group -- `formwork` itself
        // and whatever shares its job (characterization C6). Listing pids stays allowed: `sysctl`
        // lists them regardless, and `lsof` needs the listing to find the session's own.
        b.push_str("(deny process-info*)\n");
        b.push_str("(allow process-info-listpids)\n");
        b.push_str("(allow process-info* (target same-sandbox))\n");
        b.push_str("(deny signal)\n");
        b.push_str("(allow signal (target same-sandbox))\n");
    }
    if isolate.contains(&IsolateMember::Ipc) {
        b.push_str("(deny ipc-sysv*)\n");
    }
}

/// Seatbelt classifies an AF_UNIX connect as `network-outbound`, so FW-ISO3's `(deny network*)`
/// also blocks `getaddrinfo` -- an FW-ISO5 port tier would reach literal IPs only. A literal, not
/// `(remote unix-socket)`: a blanket unix grant would also open the Docker socket and ssh-agent.
/// Public so the confiner's resolver probe asserts against the very literal the rule grants.
pub const MACOS_RESOLVER_SOCKET: &str = "/private/var/run/mDNSResponder";

fn render_net(
    b: &mut String,
    net: &NetPosture,
    gateway_port: Option<u16>,
    unix_grants: &[PathPattern],
) {
    b.push_str("\n;; net: fail-closed egress (FW-ISO3)\n");
    b.push_str("(deny network*)\n");
    // FW-EGR15: a confined login flow accepts the callback an unconfined browser makes to it.
    b.push_str(";; loopback listen under every posture (FW-EGR15)\n");
    b.push_str("(allow network-bind (local ip \"localhost:*\"))\n");
    b.push_str("(allow network-inbound (local ip \"localhost:*\"))\n");
    if let NetPosture::AllowHosts(_) = net {
        // FW-EGR8: the session's Gateway listener is the only outbound endpoint. SBPL remote
        // filters take `*` or `localhost` as the host, so the listener authenticates itself
        // (FW-EGR9). No resolver literal: lookups happen in the Gateway (FW-EGR12).
        b.push_str(";; host-scoped egress: the session Gateway is the sole endpoint (FW-EGR8)\n");
        match gateway_port {
            Some(p) => b.push_str(&format!(
                "(allow network-outbound (remote tcp \"localhost:{p}\"))\n"
            )),
            None => b.push_str(";; (gateway port assigned at spawn; none in a dry run)\n"),
        }
    }
    if !unix_grants.is_empty() {
        b.push_str(";; granted pathname sockets (FW-ISO12)\n");
        for p in unix_grants {
            b.push_str(&format!(
                "(allow network-outbound (literal \"{}\"))\n",
                escape(&p.base().display().to_string())
            ));
        }
    }
    if let NetPosture::Ports(ports) = net {
        if !ports.is_empty() {
            b.push_str(";; optional direct TCP port tier (FW-ISO5)\n");
            for p in ports {
                b.push_str(&format!(
                    "(allow network-outbound (remote tcp \"*:{p}\"))\n"
                ));
            }
            // Port tier only: under FW-ISO3 deny a reachable resolver would leak looked-up names.
            b.push_str(";; DNS: the resolver socket the port tier is useless without\n");
            b.push_str(&format!(
                "(allow network-outbound (literal \"{MACOS_RESOLVER_SOCKET}\"))\n"
            ));
        }
    }
}

/// System paths a confined process must read for the ambient toolchain to start: dyld, the shared
/// cache, frameworks, and standard binary locations. Without these, `(deny file-read* (subpath
/// "/"))` stops `execve`'d programs loading their own code. Runtime dirs, not user data -- secrets
/// live under `$HOME`, which stays denied -- and any `subtract` hole still wins (emitted last).
const MACOS_READ_ESSENTIALS: &[&str] = &[
    // D11: configuration every runtime reads (resolv.conf, hosts, ssl); the absolute floor rows
    // under it (/etc/shadow, /etc/sudoers) are still denied, emitted after the grants.
    "/private/etc",
    "/System",
    "/Library",
    "/bin",
    "/sbin",
    "/usr/bin",
    "/usr/lib",
    "/usr/sbin",
    "/usr/share",
    "/private/var/db/dyld",
    "/private/preboot",
    "/System/Volumes/Preboot/Cryptexes",
];

/// Safe device nodes read at startup (notably `/dev/urandom`, without which CPython aborts during
/// hash-randomization init). Literals only, never `(subpath "/dev")`: a broad `/dev` grant exposes
/// `/dev/rdisk*` (the raw disk) and would let a confined process read the whole filesystem.
const MACOS_READ_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/random",
    "/dev/urandom",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/autofs_nowait",
    "/dev/fd",
    "/dev/stdin",
    "/dev/stdout",
    "/dev/stderr",
];

/// Safe writable device nodes. Same literals-only rule as reads: no raw disks or arbitrary `/dev`.
const MACOS_WRITE_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/stdout",
    "/dev/stderr",
    "/dev/fd",
];

/// The `file-write-*` ops a `modify` grant allows: everything except `file-write-create` (FW-CAP9).
/// Create stays denied by the root `(deny file-write* ...)`, which nothing here re-allows.
const MACOS_WRITE_NO_CREATE_OPS: &[&str] = &[
    "file-write-data",
    "file-write-flags",
    "file-write-mode",
    "file-write-owner",
    "file-write-setugid",
    "file-write-times",
    "file-write-unlink",
];

fn render_reads(
    b: &mut String,
    mode: ReadMode,
    reads: &[PathPattern],
    subtract: &[PathPattern],
    floor: &[PathPattern],
    floor_exempt: &[PathPattern],
) {
    b.push_str("\n;; reads\n");
    match mode {
        ReadMode::Closed => {
            b.push_str("(deny file-read* (subpath \"/\"))\n");
            // Metadata (stat) stays broadly readable: Formwork denies with EACCES not ENOENT
            // (FW-CAP4), and many tools stat optional paths and continue (FW-TRA4).
            b.push_str("(allow file-read-metadata)\n");
            // The root inode itself must be readable (dyld/loader traverse it); the `/` literal
            // only, not its subtree, so denied subdirs stay denied.
            b.push_str("(allow file-read* (literal \"/\"))\n");
            b.push_str(";; system runtime essentials (so the ambient toolchain can load & run)\n");
            for p in MACOS_READ_ESSENTIALS {
                b.push_str(&format!("(allow file-read* (subpath \"{p}\"))\n"));
            }
            b.push_str(";; safe device nodes (curated literals; never a broad /dev)\n");
            for p in MACOS_READ_DEVICES {
                b.push_str(&format!("(allow file-read* (literal \"{p}\"))\n"));
            }
            b.push_str(";; user grants\n");
            for p in reads {
                b.push_str(&format!("(allow file-read* {})\n", filter(p)));
            }
        }
        ReadMode::AmbientMinusSubtract => {
            b.push_str(";; ambient reads (allow default); only subtract holes below\n");
        }
    }
    // Floor and subtract holes deny read AND metadata: a confined process must not learn a
    // credential file's existence, size, or mtime via `stat` (FW-CAP7). The explicit metadata deny
    // is required because Closed mode's broad `(allow file-read-metadata)` (kept for FW-TRA4) would
    // otherwise re-admit it -- last-match-wins does not fold `file-read-metadata` into a
    // `file-read*` deny here.
    if !floor.is_empty() {
        b.push_str(";; credential-catalog floor (FW-CRED4)\n");
    }
    for p in floor {
        let f = filter(p);
        b.push_str(&format!("(deny file-read* {f})\n"));
        b.push_str(&format!("(deny file-read-metadata {f})\n"));
    }
    // Typed exclusions re-lift the floor inside the excluded type's own scope (the any-depth
    // backstop is what crosses in). Clamped to the grant surface in Closed mode so an exclusion
    // never grants what the blueprint didn't.
    let exempt = match mode {
        ReadMode::AmbientMinusSubtract => floor_exempt.to_vec(),
        ReadMode::Closed => intersect_grants(floor_exempt, reads),
    };
    if !exempt.is_empty() {
        b.push_str(";; typed credential exclusions (FW-CRED5)\n");
    }
    for p in &exempt {
        let f = filter(p);
        b.push_str(&format!("(allow file-read* {f})\n"));
        b.push_str(&format!("(allow file-read-metadata {f})\n"));
    }
    for p in subtract {
        let f = filter(p);
        b.push_str(&format!("(deny file-read* {f})\n"));
        b.push_str(&format!("(deny file-read-metadata {f})\n"));
    }
}

fn render_writes(
    b: &mut String,
    writes: &[PathPattern],
    writes_no_create: &[PathPattern],
    subtract: &[PathPattern],
    write_subtract: &[PathPattern],
    floor: &[PathPattern],
    floor_exempt: &[PathPattern],
) {
    b.push_str("\n;; writes: always closed (FW-ISO2, FW-TRA5)\n");
    b.push_str("(deny file-write* (subpath \"/\"))\n");
    b.push_str(";; safe writable device nodes (curated literals; e.g. `cmd > /dev/null`)\n");
    for p in MACOS_WRITE_DEVICES {
        b.push_str(&format!("(allow file-write* (literal \"{p}\"))\n"));
    }
    for p in writes {
        b.push_str(&format!("(allow file-write* {})\n", filter(p)));
    }
    // Before the floor/subtract denies, so those still win by last-match (FW-CAP9).
    if !writes_no_create.is_empty() {
        b.push_str(";; write, no create (FW-CAP9): modify existing, never create\n");
        for p in writes_no_create {
            let f = filter(p);
            for op in MACOS_WRITE_NO_CREATE_OPS {
                b.push_str(&format!("(allow {op} {f})\n"));
            }
        }
    }
    for p in floor {
        b.push_str(&format!("(deny file-write* {})\n", filter(p)));
    }
    // Writes are always closed, so the exclusion re-allow clamps to the write grants.
    for p in &intersect_grants(floor_exempt, writes) {
        b.push_str(&format!("(allow file-write* {})\n", filter(p)));
    }
    for p in subtract {
        b.push_str(&format!("(deny file-write* {})\n", filter(p)));
    }
    // Tamper vectors: write-denied but NOT read-denied, so tooling still reads them (FW-TRA7). These
    // deny file-write* only; render_reads never sees write_subtract.
    if !write_subtract.is_empty() {
        b.push_str(";; write-only tamper-vector denials -- readable, not writable (FW-TRA7)\n");
        for p in write_subtract {
            b.push_str(&format!("(deny file-write* {})\n", filter(p)));
        }
    }
}

fn render_exec(b: &mut String, exec: &ExecPosture) {
    if let ExecPosture::Allowlist(paths) = exec {
        b.push_str("\n;; exec allow-list (FW-ISO4)\n");
        b.push_str("(deny process-exec* (subpath \"/\"))\n");
        for p in paths {
            b.push_str(&format!("(allow process-exec* {})\n", filter(p)));
        }
    }
}

fn filter(p: &PathPattern) -> String {
    if p.is_any_depth() {
        return format!("(regex #\"{}\")", any_depth_regex(p));
    }
    let path = escape(&p.base().display().to_string());
    if p.is_subtree() {
        format!("(subpath \"{path}\")")
    } else {
        format!("(literal \"{path}\")")
    }
}

/// An any-depth pattern (FW-CAP6) matches its suffix at any depth. Seatbelt regexes are
/// unanchored, so for the plain form a leading `/` before the first component pins a component
/// boundary and the trailing `$` (literal) or `(/|$)` (subtree) pins the end, while the start is
/// free to match at any depth: `**/.env` -> `/\.env$`. The prefix-anchored form pins the start
/// too, with zero-or-more directories between: `/home/x/**/credentials` ->
/// `^/home/x/(.*/)?credentials$`.
fn any_depth_regex(p: &PathPattern) -> String {
    let mut body = String::new();
    if let Some(anchor) = p.anchor() {
        body.push('^');
        for comp in anchor.components() {
            if let std::path::Component::Normal(c) = comp {
                body.push('/');
                body.push_str(&regex_escape(&c.to_string_lossy()));
            }
        }
        body.push_str("/(.*/)?");
        let mut first = true;
        for comp in p.base().components() {
            if !first {
                body.push('/');
            }
            first = false;
            body.push_str(&regex_escape(&comp.as_os_str().to_string_lossy()));
        }
    } else {
        for comp in p.base().components() {
            body.push('/');
            body.push_str(&regex_escape(&comp.as_os_str().to_string_lossy()));
        }
    }
    if p.is_subtree() {
        body.push_str("(/|$)");
    } else {
        body.push('$');
    }
    body
}

fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(
            c,
            '.' | '^'
                | '$'
                | '*'
                | '+'
                | '?'
                | '('
                | ')'
                | '['
                | ']'
                | '{'
                | '}'
                | '|'
                | '\\'
                | '"'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CompileInput;
    use formwork_blueprint::{ExecPosture, NetPosture, ReadMode};

    fn pp(s: &str) -> PathPattern {
        PathPattern::parse(s).unwrap()
    }

    fn input() -> CompileInput {
        CompileInput {
            floor: Vec::new(),
            floor_exempt: Vec::new(),
            read_mode: ReadMode::Closed,
            effective_reads: vec![pp("/work/project/**")],
            writes: vec![pp("/work/project/**")],
            writes_no_create: vec![],
            subtract: vec![pp("/work/project/.git/**")],
            write_subtract: vec![],
            net: NetPosture::Deny,
            exec: ExecPosture::Unrestricted,
            channels: ChannelPolicy::default(),
            isolate: Vec::new(),
            gateway_port: None,
            session_marker: None,
            unix_socket_grants: Vec::new(),
            brokered: false,
            keyring_lifted: false,
            keyring_services: vec!["com.apple.SecurityServer".to_string()],
        }
    }

    #[test]
    fn writes_no_create_allows_modify_but_not_create() {
        // FW-CAP9 create/write split: a `modify` grant renders every file-write op except create.
        let mut i = input();
        i.writes = vec![];
        i.writes_no_create = vec![pp("/data/**")];
        let s = render(&i);
        assert!(s.contains("(allow file-write-data (subpath \"/data\"))"));
        assert!(s.contains("(allow file-write-unlink (subpath \"/data\"))"));
        assert!(s.contains("(allow file-write-mode (subpath \"/data\"))"));
        // Create is never granted; the root `(deny file-write* ...)` keeps it denied.
        assert!(!s.contains("file-write-create (subpath \"/data\")"));
        // And no blanket file-write* allow that would re-admit create.
        assert!(!s.contains("(allow file-write* (subpath \"/data\"))"));
    }

    #[test]
    fn floor_denies_then_exempt_reallows_then_operator_denies() {
        // Last-match-wins: floor < typed exemption < operator subtract (FW-CRED4/5, FW-BP4).
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.floor = vec![pp("**/credentials"), pp("/home/x/.ssh/**")];
        i.floor_exempt = vec![pp("/home/x/.aws/**")];
        let s = render(&i);
        let floor_deny = s
            .find("(deny file-read* (regex #\"/credentials$\"))")
            .unwrap();
        let exempt_allow = s
            .find("(allow file-read* (subpath \"/home/x/.aws\"))")
            .unwrap();
        let operator_deny = s
            .find("(deny file-read* (subpath \"/work/project/.git\"))")
            .unwrap();
        assert!(
            floor_deny < exempt_allow,
            "exemption must be able to lift the floor"
        );
        assert!(
            exempt_allow < operator_deny,
            "operator subtract must win over the exemption"
        );
    }

    #[test]
    fn anchored_any_depth_renders_a_start_pinned_regex() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.floor = vec![pp("/home/x/**/credentials"), pp("/home/x/**/.git/hooks/**")];
        let s = render(&i);
        assert!(
            s.contains("(deny file-read* (regex #\"^/home/x/(.*/)?credentials$\"))"),
            "{s}"
        );
        assert!(
            s.contains("(deny file-read* (regex #\"^/home/x/(.*/)?\\.git/hooks(/|$)\"))"),
            "{s}"
        );
    }

    #[test]
    fn closed_mode_clamps_exemption_to_the_grant_surface() {
        // reads grant only /work/project; an excluded ~/.aws must NOT be re-allowed in closed
        // mode -- the exclusion lifts the floor, it never grants (FW-CRED5).
        let mut i = input();
        i.floor = vec![pp("**/credentials")];
        i.floor_exempt = vec![pp("/home/x/.aws/**")];
        let s = render(&i);
        assert!(
            !s.contains("/home/x/.aws"),
            "unclamped exemption widened a closed grant:\n{s}"
        );
    }

    #[test]
    fn closed_reads_deny_root_then_allow_grants() {
        let s = render(&input());
        assert!(s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(allow file-read* (subpath \"/work/project\"))"));
        // subtract hole after grant (deny wins under last-match)
        let allow_idx = s
            .find("(allow file-read* (subpath \"/work/project\"))")
            .unwrap();
        let deny_idx = s
            .find("(deny file-read* (subpath \"/work/project/.git\"))")
            .unwrap();
        assert!(
            deny_idx > allow_idx,
            "subtract hole must come after the grant"
        );
    }

    #[test]
    fn net_denied_by_default() {
        let s = render(&input());
        assert!(s.contains("(deny network*)"));
        assert!(!s.contains("network-outbound"));
        // FW-EGR15: loopback listen stays open under every posture.
        assert!(s.contains("(allow network-inbound (local ip \"localhost:*\"))"));
    }

    #[test]
    fn baseline_denies_channels_until_lifted_and_never_lifts_launchservices() {
        let s = render(&input());
        assert!(s.contains("(deny appleevent-send)"));
        assert!(s.contains("(deny lsopen)"));
        assert!(s.contains("com\\.apple\\.pasteboard"));
        assert!(s.contains("(deny mach-priv-task-port)"));
        assert!(
            s.contains("com.apple.windowserver.active"),
            "screen capture goes through WindowServer (C3)"
        );
        assert!(s.contains("(deny job-creation)"));
        let mut i = input();
        i.channels = ChannelPolicy::allow([Channel::Clipboard, Channel::OpenUrl]);
        let lifted = render(&i);
        assert!(
            !lifted.contains("pasteboard"),
            "a lifted channel drops its deny"
        );
        assert!(
            lifted.contains("(deny lsopen)"),
            "open-url is brokered, LaunchServices stays denied (FW-ISO18)"
        );
    }

    #[test]
    fn host_rules_allow_only_the_gateway_endpoint_and_drop_the_resolver() {
        let mut i = input();
        i.net = NetPosture::AllowHosts(formwork_blueprint::HostTable::new(vec![
            serde_json::from_str("\"allow:api.anthropic.com\"").unwrap(),
        ]));
        i.gateway_port = Some(41234);
        let s = render(&i);
        assert!(s.contains("(allow network-outbound (remote tcp \"localhost:41234\"))"));
        assert!(!s.contains(MACOS_RESOLVER_SOCKET));
        i.gateway_port = None;
        assert!(
            !render(&i).contains("remote tcp"),
            "a dry run allows no endpoint"
        );
    }

    #[test]
    fn the_keychain_is_denied_until_os_keyring_is_lifted() {
        let deny = "(deny mach-lookup (global-name \"com.apple.SecurityServer\"))";
        assert!(render(&input()).contains(deny));
        let mut i = input();
        i.keyring_lifted = true;
        assert!(!render(&i).contains("com.apple.SecurityServer"));
    }

    #[test]
    fn the_session_marker_is_rendered_last() {
        let mut i = input();
        i.session_marker = Some(crate::SessionMarker::new("abc123"));
        let s = render(&i);
        let tail = s.trim_end().rsplit_once(";; session marker").unwrap().1;
        assert!(tail.contains("(deny mach-lookup (global-name \"dev.formwork.session.abc123.d\"))"));
        assert!(
            tail.contains("(allow mach-lookup (global-name \"dev.formwork.session.abc123.a\"))")
        );
        assert!(!render(&input()).contains("dev.formwork.session"));
    }

    #[test]
    fn isolate_processes_denies_others_and_keeps_the_session() {
        let mut i = input();
        i.isolate = vec![IsolateMember::Processes, IsolateMember::Ipc];
        let s = render(&i);
        assert!(s.contains("(deny signal)\n(allow signal (target same-sandbox))"));
        assert!(s.contains("(allow process-info* (target same-sandbox))"));
        assert!(s.contains("(deny ipc-sysv*)"));
        assert!(!render(&input()).contains("same-sandbox"));
    }

    #[test]
    fn port_tier_reallows_outbound() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![8080]);
        let s = render(&i);
        assert!(s.contains("(allow network-outbound (remote tcp \"*:8080\"))"));
    }

    /// The resolver rule rides with the port tier and only with it -- `net_denied_by_default` above
    /// pins the deny half by asserting no `network-outbound` line at all.
    #[test]
    fn port_tier_reallows_resolver_socket() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![443]);
        let s = render(&i);
        assert!(s.contains(&format!(
            "(allow network-outbound (literal \"{MACOS_RESOLVER_SOCKET}\"))"
        )));
    }

    /// An empty port list is a tier that grants nothing, so it must not smuggle the resolver through.
    #[test]
    fn empty_port_tier_grants_no_resolver() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![]);
        let s = render(&i);
        assert!(!s.contains("network-outbound"));
    }

    #[test]
    fn ambient_reads_skip_root_deny() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        let s = render(&i);
        assert!(!s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(deny file-read* (subpath \"/work/project/.git\"))"));
    }

    #[test]
    fn writes_always_closed() {
        let s = render(&input());
        assert!(s.contains("(deny file-write* (subpath \"/\"))"));
        assert!(s.contains("(allow file-write* (subpath \"/work/project\"))"));
    }

    #[test]
    fn exec_allowlist_rendered_only_when_set() {
        assert!(!render(&input()).contains("process-exec*"));
        let mut i = input();
        i.exec = ExecPosture::Allowlist(vec![pp("/usr/bin/git")]);
        let s = render(&i);
        assert!(s.contains("(deny process-exec* (subpath \"/\"))"));
        assert!(s.contains("(allow process-exec* (literal \"/usr/bin/git\"))"));
    }

    #[test]
    fn write_subtract_denies_write_but_not_read() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![];
        i.write_subtract = vec![pp("**/.git/hooks/**"), pp("**/.mcp.json")];
        let s = render(&i);
        // write is denied for the tamper vectors...
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
        // ...but read is NOT denied (tooling still reads .git/config, hooks, etc.).
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
    }

    #[test]
    fn any_depth_subtract_renders_as_regex() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![pp("**/.env"), pp("**/.git/hooks/**")];
        let s = render(&i);
        // literal suffix pins the end; subtree suffix matches the dir and anything under it.
        assert!(s.contains(r#"(deny file-read* (regex #"/\.env$"))"#), "{s}");
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
    }
}
