//! Deterministic SBPL (Seatbelt profile language) generation for the macOS confiner.
//!
//! SBPL is last-match-wins, so ordering encodes the policy: `(allow default)` for transparency
//! (FW-TRA2), then `(deny network*)` + optional port re-allows, then reads, writes, exec. Within
//! each fs section the order is: grants, credential-floor denies (FW-CRED4), typed-exclusion
//! re-allows clamped to the grant surface (FW-CRED5 -- so `--allow-cred aws` lifts the any-depth
//! backstop inside `~/.aws/**` without widening anything), then operator subtract holes last --
//! an operator deny is never lifted by anything.

use formwork_blueprint::{intersect_grants, ExecPosture, NetPosture, PathPattern, ReadMode};

use crate::CompileInput;

/// Pure and deterministic.
pub fn render(input: &CompileInput) -> String {
    let mut b = String::new();
    b.push_str("(version 1)\n");
    b.push_str(";; Generated by formwork-compile. Do not edit.\n");
    b.push_str("(allow default)\n");

    render_net(&mut b, &input.net);
    render_reads(
        &mut b,
        input.read_mode,
        &input.effective_reads,
        &input.subtract,
        &input.floor,
        &input.floor_exempt,
    );
    render_writes(
        &mut b,
        &input.writes,
        &input.writes_no_create,
        &input.subtract,
        &input.write_subtract,
        &input.floor,
        &input.floor_exempt,
    );
    render_exec(&mut b, &input.exec);

    b
}

/// Seatbelt classifies an AF_UNIX connect as `network-outbound`, so FW-ISO3's `(deny network*)`
/// also blocks `getaddrinfo` -- an FW-ISO5 port tier would reach literal IPs only. A literal, not
/// `(remote unix-socket)`: a blanket unix grant would also open the Docker socket and ssh-agent.
/// Public so the confiner's resolver probe asserts against the very literal the rule grants.
pub const MACOS_RESOLVER_SOCKET: &str = "/private/var/run/mDNSResponder";

fn render_net(b: &mut String, net: &NetPosture) {
    b.push_str("\n;; net: fail-closed egress (FW-ISO3)\n");
    b.push_str("(deny network*)\n");
    if let NetPosture::Ports(ports) = net {
        if !ports.is_empty() {
            b.push_str(";; optional direct TCP port tier (FW-ISO5)\n");
            for p in ports {
                b.push_str(&format!(
                    "(allow network-outbound (remote tcp \"*:{p}\"))\n"
                ));
            }
            // Port tier only: under FW-ISO3 deny a reachable resolver would leak looked-up names.
            b.push_str(";; DNS: the resolver socket the port tier is useless without\n");
            b.push_str(&format!(
                "(allow network-outbound (literal \"{MACOS_RESOLVER_SOCKET}\"))\n"
            ));
        }
    }
}

/// System paths a confined process must read for the ambient toolchain to start: dyld, the shared
/// cache, frameworks, and standard binary locations. Without these, `(deny file-read* (subpath
/// "/"))` stops `execve`'d programs loading their own code. Runtime dirs, not user data -- secrets
/// live under `$HOME`, which stays denied -- and any `subtract` hole still wins (emitted last).
const MACOS_READ_ESSENTIALS: &[&str] = &[
    "/System",
    "/Library",
    "/bin",
    "/sbin",
    "/usr/bin",
    "/usr/lib",
    "/usr/sbin",
    "/usr/share",
    "/private/var/db/dyld",
    "/private/preboot",
    "/System/Volumes/Preboot/Cryptexes",
];

/// Safe device nodes read at startup (notably `/dev/urandom`, without which CPython aborts during
/// hash-randomization init). Literals only, never `(subpath "/dev")`: a broad `/dev` grant exposes
/// `/dev/rdisk*` (the raw disk) and would let a confined process read the whole filesystem.
const MACOS_READ_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/random",
    "/dev/urandom",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/autofs_nowait",
    "/dev/fd",
    "/dev/stdin",
    "/dev/stdout",
    "/dev/stderr",
];

/// Safe writable device nodes. Same literals-only rule as reads: no raw disks or arbitrary `/dev`.
const MACOS_WRITE_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/stdout",
    "/dev/stderr",
    "/dev/fd",
];

/// The `file-write-*` ops a `modify` grant allows: everything except `file-write-create` (FW-CAP9).
/// Create stays denied by the root `(deny file-write* ...)`, which nothing here re-allows.
const MACOS_WRITE_NO_CREATE_OPS: &[&str] = &[
    "file-write-data",
    "file-write-flags",
    "file-write-mode",
    "file-write-owner",
    "file-write-setugid",
    "file-write-times",
    "file-write-unlink",
];

fn render_reads(
    b: &mut String,
    mode: ReadMode,
    reads: &[PathPattern],
    subtract: &[PathPattern],
    floor: &[PathPattern],
    floor_exempt: &[PathPattern],
) {
    b.push_str("\n;; reads\n");
    match mode {
        ReadMode::Closed => {
            b.push_str("(deny file-read* (subpath \"/\"))\n");
            // Metadata (stat) stays broadly readable: Formwork denies with EACCES not ENOENT
            // (FW-CAP4), and many tools stat optional paths and continue (FW-TRA4).
            b.push_str("(allow file-read-metadata)\n");
            // The root inode itself must be readable (dyld/loader traverse it); the `/` literal
            // only, not its subtree, so denied subdirs stay denied.
            b.push_str("(allow file-read* (literal \"/\"))\n");
            b.push_str(";; system runtime essentials (so the ambient toolchain can load & run)\n");
            for p in MACOS_READ_ESSENTIALS {
                b.push_str(&format!("(allow file-read* (subpath \"{p}\"))\n"));
            }
            b.push_str(";; safe device nodes (curated literals; never a broad /dev)\n");
            for p in MACOS_READ_DEVICES {
                b.push_str(&format!("(allow file-read* (literal \"{p}\"))\n"));
            }
            b.push_str(";; user grants\n");
            for p in reads {
                b.push_str(&format!("(allow file-read* {})\n", filter(p)));
            }
        }
        ReadMode::AmbientMinusSubtract => {
            b.push_str(";; ambient reads (allow default); only subtract holes below\n");
        }
    }
    // Floor and subtract holes deny read AND metadata: a confined process must not learn a
    // credential file's existence, size, or mtime via `stat` (FW-CAP7). The explicit metadata deny
    // is required because Closed mode's broad `(allow file-read-metadata)` (kept for FW-TRA4) would
    // otherwise re-admit it -- last-match-wins does not fold `file-read-metadata` into a
    // `file-read*` deny here.
    if !floor.is_empty() {
        b.push_str(";; credential-catalog floor (FW-CRED4)\n");
    }
    for p in floor {
        let f = filter(p);
        b.push_str(&format!("(deny file-read* {f})\n"));
        b.push_str(&format!("(deny file-read-metadata {f})\n"));
    }
    // Typed exclusions re-lift the floor inside the excluded type's own scope (the any-depth
    // backstop is what crosses in). Clamped to the grant surface in Closed mode so an exclusion
    // never grants what the blueprint didn't.
    let exempt = match mode {
        ReadMode::AmbientMinusSubtract => floor_exempt.to_vec(),
        ReadMode::Closed => intersect_grants(floor_exempt, reads),
    };
    if !exempt.is_empty() {
        b.push_str(";; typed credential exclusions (FW-CRED5)\n");
    }
    for p in &exempt {
        let f = filter(p);
        b.push_str(&format!("(allow file-read* {f})\n"));
        b.push_str(&format!("(allow file-read-metadata {f})\n"));
    }
    for p in subtract {
        let f = filter(p);
        b.push_str(&format!("(deny file-read* {f})\n"));
        b.push_str(&format!("(deny file-read-metadata {f})\n"));
    }
}

fn render_writes(
    b: &mut String,
    writes: &[PathPattern],
    writes_no_create: &[PathPattern],
    subtract: &[PathPattern],
    write_subtract: &[PathPattern],
    floor: &[PathPattern],
    floor_exempt: &[PathPattern],
) {
    b.push_str("\n;; writes: always closed (FW-ISO2, FW-TRA5)\n");
    b.push_str("(deny file-write* (subpath \"/\"))\n");
    b.push_str(";; safe writable device nodes (curated literals; e.g. `cmd > /dev/null`)\n");
    for p in MACOS_WRITE_DEVICES {
        b.push_str(&format!("(allow file-write* (literal \"{p}\"))\n"));
    }
    for p in writes {
        b.push_str(&format!("(allow file-write* {})\n", filter(p)));
    }
    // Before the floor/subtract denies, so those still win by last-match (FW-CAP9).
    if !writes_no_create.is_empty() {
        b.push_str(";; write, no create (FW-CAP9): modify existing, never create\n");
        for p in writes_no_create {
            let f = filter(p);
            for op in MACOS_WRITE_NO_CREATE_OPS {
                b.push_str(&format!("(allow {op} {f})\n"));
            }
        }
    }
    for p in floor {
        b.push_str(&format!("(deny file-write* {})\n", filter(p)));
    }
    // Writes are always closed, so the exclusion re-allow clamps to the write grants.
    for p in &intersect_grants(floor_exempt, writes) {
        b.push_str(&format!("(allow file-write* {})\n", filter(p)));
    }
    for p in subtract {
        b.push_str(&format!("(deny file-write* {})\n", filter(p)));
    }
    // Tamper vectors: write-denied but NOT read-denied, so tooling still reads them (FW-TRA7). These
    // deny file-write* only; render_reads never sees write_subtract.
    if !write_subtract.is_empty() {
        b.push_str(";; write-only tamper-vector denials -- readable, not writable (FW-TRA7)\n");
        for p in write_subtract {
            b.push_str(&format!("(deny file-write* {})\n", filter(p)));
        }
    }
}

fn render_exec(b: &mut String, exec: &ExecPosture) {
    if let ExecPosture::Allowlist(paths) = exec {
        b.push_str("\n;; exec allow-list (FW-ISO4)\n");
        b.push_str("(deny process-exec* (subpath \"/\"))\n");
        for p in paths {
            b.push_str(&format!("(allow process-exec* {})\n", filter(p)));
        }
    }
}

fn filter(p: &PathPattern) -> String {
    if p.is_any_depth() {
        return format!("(regex #\"{}\")", any_depth_regex(p));
    }
    let path = escape(&p.base().display().to_string());
    if p.is_subtree() {
        format!("(subpath \"{path}\")")
    } else {
        format!("(literal \"{path}\")")
    }
}

/// An any-depth pattern (FW-CAP6) matches its suffix at any depth. Seatbelt regexes are
/// unanchored, so for the plain form a leading `/` before the first component pins a component
/// boundary and the trailing `$` (literal) or `(/|$)` (subtree) pins the end, while the start is
/// free to match at any depth: `**/.env` -> `/\.env$`. The prefix-anchored form pins the start
/// too, with zero-or-more directories between: `/home/x/**/credentials` ->
/// `^/home/x/(.*/)?credentials$`.
fn any_depth_regex(p: &PathPattern) -> String {
    let mut body = String::new();
    if let Some(anchor) = p.anchor() {
        body.push('^');
        for comp in anchor.components() {
            if let std::path::Component::Normal(c) = comp {
                body.push('/');
                body.push_str(&regex_escape(&c.to_string_lossy()));
            }
        }
        body.push_str("/(.*/)?");
        let mut first = true;
        for comp in p.base().components() {
            if !first {
                body.push('/');
            }
            first = false;
            body.push_str(&regex_escape(&comp.as_os_str().to_string_lossy()));
        }
    } else {
        for comp in p.base().components() {
            body.push('/');
            body.push_str(&regex_escape(&comp.as_os_str().to_string_lossy()));
        }
    }
    if p.is_subtree() {
        body.push_str("(/|$)");
    } else {
        body.push('$');
    }
    body
}

fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(
            c,
            '.' | '^'
                | '$'
                | '*'
                | '+'
                | '?'
                | '('
                | ')'
                | '['
                | ']'
                | '{'
                | '}'
                | '|'
                | '\\'
                | '"'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CompileInput;
    use formwork_blueprint::{ExecPosture, NetPosture, ReadMode};

    fn pp(s: &str) -> PathPattern {
        PathPattern::parse(s).unwrap()
    }

    fn input() -> CompileInput {
        CompileInput {
            floor: Vec::new(),
            floor_exempt: Vec::new(),
            read_mode: ReadMode::Closed,
            effective_reads: vec![pp("/work/project/**")],
            writes: vec![pp("/work/project/**")],
            writes_no_create: vec![],
            subtract: vec![pp("/work/project/.git/**")],
            write_subtract: vec![],
            net: NetPosture::Deny,
            exec: ExecPosture::Unrestricted,
        }
    }

    #[test]
    fn writes_no_create_allows_modify_but_not_create() {
        // FW-CAP9 create/write split: a `modify` grant renders every file-write op except create.
        let mut i = input();
        i.writes = vec![];
        i.writes_no_create = vec![pp("/data/**")];
        let s = render(&i);
        assert!(s.contains("(allow file-write-data (subpath \"/data\"))"));
        assert!(s.contains("(allow file-write-unlink (subpath \"/data\"))"));
        assert!(s.contains("(allow file-write-mode (subpath \"/data\"))"));
        // Create is never granted; the root `(deny file-write* ...)` keeps it denied.
        assert!(!s.contains("file-write-create (subpath \"/data\")"));
        // And no blanket file-write* allow that would re-admit create.
        assert!(!s.contains("(allow file-write* (subpath \"/data\"))"));
    }

    #[test]
    fn floor_denies_then_exempt_reallows_then_operator_denies() {
        // Last-match-wins: floor < typed exemption < operator subtract (FW-CRED4/5, FW-BP4).
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.floor = vec![pp("**/credentials"), pp("/home/x/.ssh/**")];
        i.floor_exempt = vec![pp("/home/x/.aws/**")];
        let s = render(&i);
        let floor_deny = s
            .find("(deny file-read* (regex #\"/credentials$\"))")
            .unwrap();
        let exempt_allow = s
            .find("(allow file-read* (subpath \"/home/x/.aws\"))")
            .unwrap();
        let operator_deny = s
            .find("(deny file-read* (subpath \"/work/project/.git\"))")
            .unwrap();
        assert!(
            floor_deny < exempt_allow,
            "exemption must be able to lift the floor"
        );
        assert!(
            exempt_allow < operator_deny,
            "operator subtract must win over the exemption"
        );
    }

    #[test]
    fn anchored_any_depth_renders_a_start_pinned_regex() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.floor = vec![pp("/home/x/**/credentials"), pp("/home/x/**/.git/hooks/**")];
        let s = render(&i);
        assert!(
            s.contains("(deny file-read* (regex #\"^/home/x/(.*/)?credentials$\"))"),
            "{s}"
        );
        assert!(
            s.contains("(deny file-read* (regex #\"^/home/x/(.*/)?\\.git/hooks(/|$)\"))"),
            "{s}"
        );
    }

    #[test]
    fn closed_mode_clamps_exemption_to_the_grant_surface() {
        // reads grant only /work/project; an excluded ~/.aws must NOT be re-allowed in closed
        // mode -- the exclusion lifts the floor, it never grants (FW-CRED5).
        let mut i = input();
        i.floor = vec![pp("**/credentials")];
        i.floor_exempt = vec![pp("/home/x/.aws/**")];
        let s = render(&i);
        assert!(
            !s.contains("/home/x/.aws"),
            "unclamped exemption widened a closed grant:\n{s}"
        );
    }

    #[test]
    fn closed_reads_deny_root_then_allow_grants() {
        let s = render(&input());
        assert!(s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(allow file-read* (subpath \"/work/project\"))"));
        // subtract hole after grant (deny wins under last-match)
        let allow_idx = s
            .find("(allow file-read* (subpath \"/work/project\"))")
            .unwrap();
        let deny_idx = s
            .find("(deny file-read* (subpath \"/work/project/.git\"))")
            .unwrap();
        assert!(
            deny_idx > allow_idx,
            "subtract hole must come after the grant"
        );
    }

    #[test]
    fn net_denied_by_default() {
        let s = render(&input());
        assert!(s.contains("(deny network*)"));
        assert!(!s.contains("network-outbound"));
    }

    #[test]
    fn port_tier_reallows_outbound() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![8080]);
        let s = render(&i);
        assert!(s.contains("(allow network-outbound (remote tcp \"*:8080\"))"));
    }

    /// The resolver rule rides with the port tier and only with it -- `net_denied_by_default` above
    /// pins the deny half by asserting no `network-outbound` line at all.
    #[test]
    fn port_tier_reallows_resolver_socket() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![443]);
        let s = render(&i);
        assert!(s.contains(&format!(
            "(allow network-outbound (literal \"{MACOS_RESOLVER_SOCKET}\"))"
        )));
    }

    /// An empty port list is a tier that grants nothing, so it must not smuggle the resolver through.
    #[test]
    fn empty_port_tier_grants_no_resolver() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![]);
        let s = render(&i);
        assert!(!s.contains("network-outbound"));
    }

    #[test]
    fn ambient_reads_skip_root_deny() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        let s = render(&i);
        assert!(!s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(deny file-read* (subpath \"/work/project/.git\"))"));
    }

    #[test]
    fn writes_always_closed() {
        let s = render(&input());
        assert!(s.contains("(deny file-write* (subpath \"/\"))"));
        assert!(s.contains("(allow file-write* (subpath \"/work/project\"))"));
    }

    #[test]
    fn exec_allowlist_rendered_only_when_set() {
        assert!(!render(&input()).contains("process-exec*"));
        let mut i = input();
        i.exec = ExecPosture::Allowlist(vec![pp("/usr/bin/git")]);
        let s = render(&i);
        assert!(s.contains("(deny process-exec* (subpath \"/\"))"));
        assert!(s.contains("(allow process-exec* (literal \"/usr/bin/git\"))"));
    }

    #[test]
    fn write_subtract_denies_write_but_not_read() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![];
        i.write_subtract = vec![pp("**/.git/hooks/**"), pp("**/.mcp.json")];
        let s = render(&i);
        // write is denied for the tamper vectors...
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
        // ...but read is NOT denied (tooling still reads .git/config, hooks, etc.).
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
    }

    #[test]
    fn any_depth_subtract_renders_as_regex() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![pp("**/.env"), pp("**/.git/hooks/**")];
        let s = render(&i);
        // literal suffix pins the end; subtree suffix matches the dir and anything under it.
        assert!(s.contains(r#"(deny file-read* (regex #"/\.env$"))"#), "{s}");
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
    }
}
