//! Deterministic SBPL (Seatbelt profile language) generation for the macOS confiner.
//!
//! SBPL is last-match-wins, so ordering encodes the policy: `(allow default)` for transparency
//! (FW-TRA2), then `(deny network*)` + optional port re-allows, then reads, writes, exec. Subtract
//! holes are emitted last within each section so a denied sensitive path wins over its grant.

use formwork_blueprint::{ExecPosture, NetPosture, PathPattern, ReadMode};

use crate::CompileInput;

/// Pure and deterministic.
pub fn render(input: &CompileInput) -> String {
    let mut b = String::new();
    b.push_str("(version 1)\n");
    b.push_str(";; Generated by formwork-compile. Do not edit.\n");
    b.push_str("(allow default)\n");

    render_net(&mut b, &input.net);
    render_reads(
        &mut b,
        input.read_mode,
        &input.effective_reads,
        &input.subtract,
    );
    render_writes(
        &mut b,
        &input.writes,
        &input.subtract,
        &input.write_subtract,
    );
    render_exec(&mut b, &input.exec);

    b
}

fn render_net(b: &mut String, net: &NetPosture) {
    b.push_str("\n;; net: fail-closed egress (FW-ISO3)\n");
    b.push_str("(deny network*)\n");
    if let NetPosture::Ports(ports) = net {
        if !ports.is_empty() {
            b.push_str(";; optional direct TCP port tier (FW-ISO5)\n");
            for p in ports {
                b.push_str(&format!(
                    "(allow network-outbound (remote tcp \"*:{p}\"))\n"
                ));
            }
        }
    }
}

/// System paths a confined process must read for the ambient toolchain to start: dyld, the shared
/// cache, frameworks, and standard binary locations. Without these, `(deny file-read* (subpath
/// "/"))` stops `execve`'d programs loading their own code. Runtime dirs, not user data -- secrets
/// live under `$HOME`, which stays denied -- and any `subtract` hole still wins (emitted last).
const MACOS_READ_ESSENTIALS: &[&str] = &[
    "/System",
    "/Library",
    "/bin",
    "/sbin",
    "/usr/bin",
    "/usr/lib",
    "/usr/sbin",
    "/usr/share",
    "/private/var/db/dyld",
    "/private/preboot",
    "/System/Volumes/Preboot/Cryptexes",
];

/// Safe device nodes read at startup (notably `/dev/urandom`, without which CPython aborts during
/// hash-randomization init). Literals only, never `(subpath "/dev")`: a broad `/dev` grant exposes
/// `/dev/rdisk*` (the raw disk) and would let a confined process read the whole filesystem.
const MACOS_READ_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/random",
    "/dev/urandom",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/autofs_nowait",
    "/dev/fd",
    "/dev/stdin",
    "/dev/stdout",
    "/dev/stderr",
];

/// Safe writable device nodes. Same literals-only rule as reads: no raw disks or arbitrary `/dev`.
const MACOS_WRITE_DEVICES: &[&str] = &[
    "/dev/null",
    "/dev/zero",
    "/dev/tty",
    "/dev/dtracehelper",
    "/dev/stdout",
    "/dev/stderr",
    "/dev/fd",
];

fn render_reads(b: &mut String, mode: ReadMode, reads: &[PathPattern], subtract: &[PathPattern]) {
    b.push_str("\n;; reads\n");
    match mode {
        ReadMode::Closed => {
            b.push_str("(deny file-read* (subpath \"/\"))\n");
            // Metadata (stat) stays broadly readable: Formwork denies with EACCES not ENOENT
            // (FW-CAP4), and many tools stat optional paths and continue (FW-TRA4).
            b.push_str("(allow file-read-metadata)\n");
            // The root inode itself must be readable (dyld/loader traverse it); the `/` literal
            // only, not its subtree, so denied subdirs stay denied.
            b.push_str("(allow file-read* (literal \"/\"))\n");
            b.push_str(";; system runtime essentials (so the ambient toolchain can load & run)\n");
            for p in MACOS_READ_ESSENTIALS {
                b.push_str(&format!("(allow file-read* (subpath \"{p}\"))\n"));
            }
            b.push_str(";; safe device nodes (curated literals; never a broad /dev)\n");
            for p in MACOS_READ_DEVICES {
                b.push_str(&format!("(allow file-read* (literal \"{p}\"))\n"));
            }
            b.push_str(";; user grants\n");
            for p in reads {
                b.push_str(&format!("(allow file-read* {})\n", filter(p)));
            }
        }
        ReadMode::AmbientMinusSubtract => {
            b.push_str(";; ambient reads (allow default); only subtract holes below\n");
        }
    }
    // Subtract holes deny read AND metadata: a confined process must not learn a credential file's
    // existence, size, or mtime via `stat` (FW-CAP7). The explicit metadata deny is required because
    // Closed mode's broad `(allow file-read-metadata)` (kept for FW-TRA4) would otherwise re-admit it
    // -- last-match-wins does not fold `file-read-metadata` into a `file-read*` deny here.
    for p in subtract {
        let f = filter(p);
        b.push_str(&format!("(deny file-read* {f})\n"));
        b.push_str(&format!("(deny file-read-metadata {f})\n"));
    }
}

fn render_writes(
    b: &mut String,
    writes: &[PathPattern],
    subtract: &[PathPattern],
    write_subtract: &[PathPattern],
) {
    b.push_str("\n;; writes: always closed (FW-ISO2, FW-TRA5)\n");
    b.push_str("(deny file-write* (subpath \"/\"))\n");
    b.push_str(";; safe writable device nodes (curated literals; e.g. `cmd > /dev/null`)\n");
    for p in MACOS_WRITE_DEVICES {
        b.push_str(&format!("(allow file-write* (literal \"{p}\"))\n"));
    }
    for p in writes {
        b.push_str(&format!("(allow file-write* {})\n", filter(p)));
    }
    for p in subtract {
        b.push_str(&format!("(deny file-write* {})\n", filter(p)));
    }
    // Tamper vectors: write-denied but NOT read-denied, so tooling still reads them (FW-TRA7). These
    // deny file-write* only; render_reads never sees write_subtract.
    if !write_subtract.is_empty() {
        b.push_str(";; write-only tamper-vector denials -- readable, not writable (FW-TRA7)\n");
        for p in write_subtract {
            b.push_str(&format!("(deny file-write* {})\n", filter(p)));
        }
    }
}

fn render_exec(b: &mut String, exec: &ExecPosture) {
    if let ExecPosture::Allowlist(paths) = exec {
        b.push_str("\n;; exec allow-list (FW-ISO4)\n");
        b.push_str("(deny process-exec* (subpath \"/\"))\n");
        for p in paths {
            b.push_str(&format!("(allow process-exec* {})\n", filter(p)));
        }
    }
}

fn filter(p: &PathPattern) -> String {
    if p.is_any_depth() {
        return format!("(regex #\"{}\")", any_depth_regex(p));
    }
    let path = escape(&p.base().display().to_string());
    if p.is_subtree() {
        format!("(subpath \"{path}\")")
    } else {
        format!("(literal \"{path}\")")
    }
}

/// A `**/`-anchored pattern (FW-CAP6) matches its suffix at any depth. Seatbelt regexes are
/// unanchored, so a leading `/` before the first component pins a component boundary and the
/// trailing `$` (literal) or `(/|$)` (subtree) pins the end, while the start is free to match at
/// any depth. E.g. `**/.env` -> `/\.env$`; `**/.git/hooks/**` -> `/\.git/hooks(/|$)`.
fn any_depth_regex(p: &PathPattern) -> String {
    let mut body = String::new();
    for comp in p.base().components() {
        body.push('/');
        body.push_str(&regex_escape(&comp.as_os_str().to_string_lossy()));
    }
    if p.is_subtree() {
        body.push_str("(/|$)");
    } else {
        body.push('$');
    }
    body
}

fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(
            c,
            '.' | '^'
                | '$'
                | '*'
                | '+'
                | '?'
                | '('
                | ')'
                | '['
                | ']'
                | '{'
                | '}'
                | '|'
                | '\\'
                | '"'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CompileInput;
    use formwork_blueprint::{ExecPosture, NetPosture, ReadMode};

    fn pp(s: &str) -> PathPattern {
        PathPattern::parse(s).unwrap()
    }

    fn input() -> CompileInput {
        CompileInput {
            read_mode: ReadMode::Closed,
            effective_reads: vec![pp("/work/project/**")],
            writes: vec![pp("/work/project/**")],
            subtract: vec![pp("/work/project/.git/**")],
            write_subtract: vec![],
            net: NetPosture::Deny,
            exec: ExecPosture::Unrestricted,
        }
    }

    #[test]
    fn closed_reads_deny_root_then_allow_grants() {
        let s = render(&input());
        assert!(s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(allow file-read* (subpath \"/work/project\"))"));
        // subtract hole after grant (deny wins under last-match)
        let allow_idx = s
            .find("(allow file-read* (subpath \"/work/project\"))")
            .unwrap();
        let deny_idx = s
            .find("(deny file-read* (subpath \"/work/project/.git\"))")
            .unwrap();
        assert!(
            deny_idx > allow_idx,
            "subtract hole must come after the grant"
        );
    }

    #[test]
    fn net_denied_by_default() {
        let s = render(&input());
        assert!(s.contains("(deny network*)"));
        assert!(!s.contains("network-outbound"));
    }

    #[test]
    fn port_tier_reallows_outbound() {
        let mut i = input();
        i.net = NetPosture::Ports(vec![8080]);
        let s = render(&i);
        assert!(s.contains("(allow network-outbound (remote tcp \"*:8080\"))"));
    }

    #[test]
    fn ambient_reads_skip_root_deny() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        let s = render(&i);
        assert!(!s.contains("(deny file-read* (subpath \"/\"))"));
        assert!(s.contains("(deny file-read* (subpath \"/work/project/.git\"))"));
    }

    #[test]
    fn writes_always_closed() {
        let s = render(&input());
        assert!(s.contains("(deny file-write* (subpath \"/\"))"));
        assert!(s.contains("(allow file-write* (subpath \"/work/project\"))"));
    }

    #[test]
    fn exec_allowlist_rendered_only_when_set() {
        assert!(!render(&input()).contains("process-exec*"));
        let mut i = input();
        i.exec = ExecPosture::Allowlist(vec![pp("/usr/bin/git")]);
        let s = render(&i);
        assert!(s.contains("(deny process-exec* (subpath \"/\"))"));
        assert!(s.contains("(allow process-exec* (literal \"/usr/bin/git\"))"));
    }

    #[test]
    fn write_subtract_denies_write_but_not_read() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![];
        i.write_subtract = vec![pp("**/.git/hooks/**"), pp("**/.mcp.json")];
        let s = render(&i);
        // write is denied for the tamper vectors...
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
        // ...but read is NOT denied (tooling still reads .git/config, hooks, etc.).
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
        assert!(
            !s.contains(r#"(deny file-read* (regex #"/\.mcp\.json$"))"#),
            "{s}"
        );
    }

    #[test]
    fn any_depth_subtract_renders_as_regex() {
        let mut i = input();
        i.read_mode = ReadMode::AmbientMinusSubtract;
        i.subtract = vec![pp("**/.env"), pp("**/.git/hooks/**")];
        let s = render(&i);
        // literal suffix pins the end; subtree suffix matches the dir and anything under it.
        assert!(s.contains(r#"(deny file-read* (regex #"/\.env$"))"#), "{s}");
        assert!(
            s.contains(r#"(deny file-write* (regex #"/\.git/hooks(/|$)"))"#),
            "{s}"
        );
    }
}
